language: php

branches:
  only:
    - master
    - develop

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - mkdir build
  - mkdir test/attachments/dir/dirdept
  - ./vendor/bin/phpunit -c test/phpunit.xml --coverage-clover build/clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/ ./config ./public/index.php

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml

matrix:
  allow_failures:
    - php: 7

sudo: false
